---
title: "GLM for count data"
author: "Laure"
date: "8 jan 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Count Data

## Count Data

Count data, in which there is no upper limit to the number of counts, usually fall into two types 

- rates counts per unit of time/area/distance, etc 
- contingency tables counts cross-classiﬁed by categorical variables

We will see that both of these types of count data can be modelled using Poisson glms with a log link.

## Poisson process

Often counts are based on events that may be assumed to arise from a Poisson process, where

- counts are observed over ﬁxed time interval

- probability of the event approximately proportional to length of time for small intervals of time

- for small intervals of time probability of > 1 event is neglibile compared to probability of one event

- numbers of events in non-overlapping time intervals are independent

Examples include number of death from lung cancer in a given year in France 

## Rate Data 

In many cases we are making comparisons across observation units $i = 1,...,n$ with diﬀerent levels of exposure to the event and hence the measure of interest is the rate of occurrence, e.g. number of death lung cancer in city $i$ in a given year in France. 

## Models for count data 

* If same exposure for all units 

$$Y_i ∼ Poisson(\lambda_i) $$
$$ E(Y_i) = \lambda_i, \hspace{1.5cm} V(Y_i) = \lambda_i $$

